# Generated by Django 5.1.7 on 2025-03-17 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role_animal_profile_report_delete_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('Board Member', 'Board Member'), ('Head Caregiver', 'Head Caregiver'), ('Caregiver', 'Caregiver'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='caregiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
